title: Sample Github Page
author: Mohammed Saayim
email: mdsaayim@gmail.com



# social links
twitter_username: twitter.com/mohammedsaayim
github_username:  github.com/mohammedsaayim

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima 
